<div class="menu">
    <ul>
        <li class="menu_item">
            <a href="<?php echo $this->getRowUrl('index')?>">Главная</a>
        </li>
        <li class="menu_item">
            <a href="<?php echo $this->getRowUrl('all')?>">Все новости</a>
        </li>
        <li class="menu_item">
            <a href="<?php echo $this->getRowUrl('source')?>">Источники</a>
        </li>        
    </ul>
</div>