<?php foreach($this->getCollection() as $itemNews):?>    
    <div class="itemNews">
<!--        <h3>        
            <a href="<?php echo $this->getRowUrl($itemNews['id']) ?>"><?php echo $itemNews['title']?></a>
        </h3>-->
        <h3>        
            <a href="<?php echo Mage::helper('test_paginator')->getRowUrl('view', array('id' => $itemNews['id'])) ?>"><?php echo $itemNews['title']?></a>
        </h3>
        <p><?php echo date('d/m/Y H:i', strtotime($itemNews['pubDate']));?></p>        
    </div>
<?php endforeach;?>