<style>
    .pagin {
        padding: 0 5px;
        font-weight: bold;
        font-size: 13px;
    }
    
    .selectPagin {
        color: #F41713; 
        padding: 0 5px;
        font-weight: bold;
        font-size: 15px;
    }
    
    .divPagin {
        text-align: center;
        margin: 25px auto;
        clear: both;
    }        
</style> 


<div class="divPagin">
    <?php if($this->_pages['hasPreviousPage']):?>
    <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $this->_pages['previousPage'] . '/' ?>" class="pagin">< Previous Page</a>
    <? endif;?>
    <?php if($this->_pages['isFirstPage']):?>    
        <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $this->_pages['firstPage'] . '/' ?>" class="pagin"><?php echo $this->_pages['firstPage']?></a> . . .        
    <?php endif;?>
    <?php for ($i = $this->_pages['startFor']; $i <= $this->_pages['endFor']; $i++):?>    
        <?php if ($i == $this->_numberPage):?>
        <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $i . '/'?>" class="selectPagin" style="color: #F41713; padding: 0px 5px;"><?php echo $i?></a>
        <?php endif;?>        
        <?php if ($i != $this->_numberPage):?>
            <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $i . '/'?>" class="pagin" style="padding: 0px 5px;"><?php echo $i . "  "?></a>        
        <?php endif;?>
    <?php endfor; ?>        
    <?php if($this->_pages['isLastPage']):?>            
         . . . <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $this->_pages['lastPage'] . '/'?>" class="pagin"><?php echo $this->_pages['lastPage']?></a>    
    <?php endif;?>
    <?php if($this->_pages['hasNextPage']):?>
        <a href="<?php echo Mage::registry('rowUrl') . 'numberPage/' . $this->_pages['nextPage'] . '/'?>" class="pagin">Next Page ></a>
    <?php endif; ?>
</div>
