<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
</head>
<body>
<style>
    .pagin {
        padding: 0 5px;
        font-weight: bold;
        font-size: 13px;
    }
    
    .selectPagin {
        color: #F41713; 
        padding: 0 5px;
        font-weight: bold;
        font-size: 15px;
    }
    
    .divPagin {
        text-align: center;
        margin: 25px auto;
        clear: both;
    }        
</style>    
    <?php foreach($this->getCollection() as $itemNews):?>    
        <div>
            <h3>        
                <a href="<?php echo $this->getRowUrl($itemNews['id']) ?>" target="_blank"><?php echo $itemNews['title']?></a>
            </h3>
            <p><?php echo date('d/m/Y H:i', strtotime($itemNews['pubDate']));?></p>
        </div>
    <?php endforeach;?>
    <div class="divPagin">
        <?php if($this->_pages['isPreviousPage']):?>
            <a href="<?php echo $this->getRowUrlPage($this->_pages['previousPage']) ?>" class="pagin">< Previous Page</a>
        <? endif;?>
        <?php if($this->_pages['isFirstpPage']):?>    
            <a href="<?php echo $this->getRowUrlPage($this->_pages['firstPage']) ?>" class="pagin"><?php echo $this->_pages['firstPage']?></a> . . .        
        <?php endif;?>
        <?php for ($i = $this->_pages['startFor']; $i <= $this->_pages['endFor']; $i++):?>    
            <?php if ($i == $this->_numberPage) :?>
                <a href="<?php echo $this->getRowUrlPage($i) ?>" class="selectPagin" style="color: #F41713; padding: 0px 5px;"><?php echo $i?></a>
            <?php endif;?>        
            <?php if ($i != $this->_numberPage) :?>
                <a href="<?php echo $this->getRowUrlPage($i) ?>" class="pagin" style="padding: 0px 5px;"><?php echo $i . "  "?></a>        
            <?php endif;?>
        <?php endfor; ?>        
        <?php if($this->_pages['isLastPage']):?>            
             . . . <a href="<?php echo $this->getRowUrlPage($this->_pages['lastPage']) ?>" class="pagin"><?php echo $this->_pages['lastPage']?></a>    
        <?php endif;?>
        <?php if($this->_pages['isNextPage']):?>
            <a href="<?php echo $this->getRowUrlPage($this->_pages['nextPage']) ?>" class="pagin">Next Page ></a>
        <?php endif; ?>
    </div>
</body>